name: Challenge 1

on: push

jobs:
  job1:
    name: Print date time in ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: "date '+%H:%M:%S   %d/%m/%y'"

  job2:
    name: Print date time in window
    runs-on: windows-latest
    steps:
      - name: print
        run: "date.exe +'%Y%m%d %H%M%S: '"

  job3:
    name: Print date time in mac
    runs-on: macos-latest
    steps:
      - name: print
        run: "date '+%H:%M:%S   %d/%m/%y'"

  job4:
    name: Print date time in ubuntu-18.04
    runs-on: ubuntu-18.04
    needs: [job1, job2, job3]
    steps:
      - name: print
        run: "date '+%H:%M:%S   %d/%m/%y'"
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: echo 'welcome to step one'
