name: Challenge 1

on: push

jobs:
  job1:
    name: Print date time in ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: "date '+%H:%M:%S   %d/%m/%y'"

  job2:
    name: Print date time in window
    runs-on: window-latest
    steps:
      - name: print
        run: "date.exe +'%Y%m%d %H%M%S: '"
